#define BUILD_COMMIT_ID "0.1-g1febccfae"
#define PROJECT_VERSION "4.0.3-beta"
#define PROJECT_VERSION_BUILD_NO "1801"
#define PROJECT_VERSION_LONG PROJECT_VERSION "." PROJECT_VERSION_BUILD_NO "(" BUILD_COMMIT_ID ")"
