#define BUILD_COMMIT_ID "0.1-g1febccfae"
#define PROJECT_VERSION "4.0.5"
#define PROJECT_VERSION_BUILD_NO "801"
#define PROJECT_VERSION_LONG PROJECT_VERSION "." PROJECT_VERSION_BUILD_NO "(" BUILD_COMMIT_ID ")"
